### 1.数组

In [1]:
import numpy as np

In [3]:
a = np.arange(15).reshape(3, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [4]:
print('数组维度数：',a.ndim)
print('数组的维度：',a.shape)

数组维度数： 2
数组的维度： (3, 5)


In [5]:
# 使用array函数将元组、列表转为array
a = np.array([2,3,4])
a

array([2, 3, 4])

In [6]:
# 多维数组
b = np.array([(1.2,3,4),(4.6,8.1,7)])
b

array([[1.2, 3. , 4. ],
       [4.6, 8.1, 7. ]])

In [7]:
# 数组的索引,顺序是先高维再低维
b[0,1] # 第1行,第2列

3.0

In [8]:
b[-1]  # 倒数第1行

array([4.6, 8.1, 7. ])

In [10]:
# 如果要对每个元素进行操作，就要使用flat属性
for i in b.flat:
    print(i)

1.2
3.0
4.0
4.6
8.1
7.0


### 2.矩阵

In [11]:
from numpy import *

In [17]:
a1 = array([[1,2,3],[2,4,5]])
print(a1)

[[1 2 3]
 [2 4 5]]


In [18]:
a2 = mat(a1)
print(a2)

[[1 2 3]
 [2 4 5]]


In [20]:
a3 = mat(random.randint(2,8,size=(2,5))) # 产生2-8的随机矩阵(2行5列)
print(a3)

[[3 3 3 4 5]
 [5 3 5 4 7]]


In [21]:
a4 = mat(random.rand(2,3)) # [0,1]之间均匀分布的随机样本
print(a4)

[[0.79425058 0.14316342 0.41055433]
 [0.59256415 0.64996507 0.35269898]]


#### numpy矩阵运算

In [36]:
A = mat(random.rand(2,2))
B = mat(random.rand(2,3))
print('B:\n',B)

B:
 [[0.10665267 0.97788274 0.87478253]
 [0.06087746 0.46929031 0.0332998 ]]


In [37]:
# 矩阵点乘
multi1 = A*B
print(multi1)

[[0.06981706 0.59776893 0.35048823]
 [0.10534252 0.95255822 0.79424219]]


In [38]:
multi2 = A.dot(B)
print(multi2)

[[0.06981706 0.59776893 0.35048823]
 [0.10534252 0.95255822 0.79424219]]


In [39]:
# 矩阵求逆
B_I = B.I
print(B_I)

[[-0.04197556  0.36274779]
 [-0.0825833   2.26675985]
 [ 1.24057529 -2.57814176]]


In [40]:
B_T = B.T
print(B_T)

[[0.10665267 0.06087746]
 [0.97788274 0.46929031]
 [0.87478253 0.0332998 ]]
